# Generated by Django 4.1 on 2022-09-19 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authenticate', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFollows',
        ),
    ]
